---
apiVersion: v1
kind: ConfigMap
metadata:
  name: global-env-vars
data:
  SELF_HOSTNAME: "http://farmers.klino.me"
  STATIC_HOST_URI: "http://farmers.klino.me"
  FEATURE_FLAG__EMAIL: "true"
  EMAIL_DEFAULT_SUBJECT: "Farmers Market"
