---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: mailer
  name: mailer
spec:
  replicas: 1
  selector:
    matchLabels:
      run: mailer
  strategy: {}
  template:
    metadata:
      labels:
        run: mailer
    spec:
      containers:
      - image: farmersregistry.azurecr.io/farmers-mailer:0.5.0
        name: mailer
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 3
          periodSeconds: 10
          failureThreshold: 1
          successThreshold: 1
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 400m
            memory: 200Mi
        envFrom:
          - configMapRef:
              name: sendgrid-env-vars
        env:
          - name: SENDGRID__API_KEY # TODO in prod, take this from a secret
            value: "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"
      dnsPolicy: ClusterFirst
status: {}
