---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: server
  strategy: {}
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - image: farmersregistry.azurecr.io/farmers-server:0.8.0
        name: server
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 60
          periodSeconds: 10
          failureThreshold: 6
          successThreshold: 1
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 1
          successThreshold: 1
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 400m
            memory: 50Mi
        envFrom:
          - configMapRef:
              name: global-env-vars
        env:
          - name: PORT
            value: "3000"
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: farmers-google-app
                key: appid
          - name: GOOGLE_APP_SECRET
            valueFrom:
              secretKeyRef:
                name: farmers-google-app
                key: secret
          - name: COOKIE_SECRET
            value: "notArealSECRET_dev_only"
          - name: MONGO__CONNECTION_STRING
            value: "mongodb://mongodb:27017"
          - name: MAILER__HOSTNAME
            value: "mailer"
          - name: MAILER__PORT
            value: "80"
          - name: MAILER__DEFAULT_ORDER_TEMPLATE
            value: "receipt-full.mjml"
      dnsPolicy: ClusterFirst
status: {}
