---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: server
  strategy: {}
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - image: farmersregistry.azurecr.io/farmers-server:0.3.0
        name: server
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 400m
            memory: 50Mi
        env:
          - name: ENVIRONMENT # NOTE this allows to login using the devadmin user
            value: "DEV"
          - name: MONGO__CONNECTION_STRING
            value: "mongodb://mongodb:27017"
          - name: DEBUG
            value: "server:*"
          - name: COOKIE_SECRET # TODO fill in from a secret
            value: "notArealSECRET_dev_only"
          - name: MAILER__HOSTNAME
            value: "mailer"
          - name: MAILER__PORT
            value: "80"
          - name: MAILER__DEFAULT_ORDER_TEMPLATE
            value: "receipt-full.mjml"
          - name: SELF_HOSTNAME # TODO pass to configmap
            value: "farmers.klino.me"
          - name: STATIC_HOST_URI # TODO pass to configmap
            value: "https://farmersstatic.blob.core.windows.net"
          - name: "FEATURE_FLAG__EMAIL" # TODO pass to configmap
            value: "true"
      dnsPolicy: ClusterFirst
status: {}
