---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: image-server
  name: image-server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: image-server
  strategy: {}
  template:
    metadata:
      labels:
        run: image-server
    spec:
      containers:
      - image: node:14.2-stretch-slim
        name: image-server
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 400m
            memory: 50Mi
        workingDir: /workspace
        command: [ "npm", "start" ]
        envFrom:
          - configMapRef:
              name: global-env-vars
        env:
          - name: "DESTINATION_DIR"
            value: "/images"
          - name: "SELF_HOSTNAME"
            value: "http://farmers.local"
        volumeMounts:
          - mountPath: /workspace
            name: image-server
          - mountPath: /images
            name: images
      volumes:
        - name: images
          persistentVolumeClaim:
            claimName: farmers-images
        - name: image-server
          hostPath:
            path: /workspace/image-server
            type: Directory
      dnsPolicy: ClusterFirst
