---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongodb
  clusterIP: None
  selector:
    app: mongodb
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  serviceName: "mongodb"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.2-bionic
          lifecycle:
            postStart:
              exec:
                command: [ '/bin/bash', '-c', '/opt/collections/script.sh' ]
          ports:
            - containerPort: 27017
              name: mongo
          readinessProbe:
            exec:
              command:
                - mongo
                - --eval
                - "db.adminCommand('ping')"
            initialDelaySeconds: 2
            periodSeconds: 10
            timeoutSeconds: 1
            successThreshold: 1
            failureThreshold: 3
          volumeMounts:
            - name: data
              mountPath: /data/db
          volumeMounts:
            - name: collections
              mountPath: /opt/collections
      volumes:
        - name: collections
          configMap:
            name: mongo-collections
            defaultMode: 0555
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: standard
        resources:
          requests:
            storage: 2Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mongo-collections
data:
  script.sh: |-
    DB_NAME="farmers"

    echo -n "waiting for mongodb to be ready"
    until mongo --eval "db.adminCommand('ping')"; do echo -n '.'; sleep 1; done;
    echo "ready"

    mongo ${DB_NAME} --eval 'db.users.createIndex( { "username": 1 }, { unique: true })'
