---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: server
  strategy: {}
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - image: node:14.2-stretch-slim
        name: server
        resources:
          requests:
            cpu: 100m
            memory: 50Mi
          limits:
            cpu: 400m
            memory: 50Mi
        workingDir: /workspace
        command: [ "npm", "start" ]
        env:
          - name: ENVIRONMENT
            value: "DEV"
          - name: COOKIE_SECRET
            value: "notArealSECRET_dev_only"
          - name: MONGO__CONNECTION_STRING
            value: "mongodb://mongodb:27017"
          - name: DEBUG
            value: "server:*"
          - name: MAILER__HOSTNAME
            value: "mailer"
          - name: MAILER__PORT
            value: "80"
          - name: MAILER__DEFAULT_ORDER_TEMPLATE
            value: "receipt-full.mjml"
          - name: SELF_HOSTNAME
            value: "farmers.local"
          - name: STATIC_HOST_URI
            value: "https://farmersstatic.blob.core.windows.net"
          - name: "FEATURE_FLAG__EMAIL"
            value: "false"
        volumeMounts:
          - mountPath: /workspace
            name: server
      volumes:
        - name: server
          hostPath:
            path: /hosthome/tomk/workspace/farmers-market/server
            type: Directory
      dnsPolicy: ClusterFirst
status: {}
