---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      run: server
  strategy: {}
  template:
    metadata:
      labels:
        run: server
    spec:
      containers:
      - image: node:14.2-stretch-slim
        name: server
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 400m
            memory: 100Mi
        workingDir: /workspace
        command: [ "npm", "run", "dev" ]
        envFrom:
          - configMapRef:
              name: global-env-vars
        env:
          - name: GOOGLE_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: farmers-google-app
                key: appid
          - name: GOOGLE_APP_SECRET
            valueFrom:
              secretKeyRef:
                name: farmers-google-app
                key: secret
          - name: COOKIE_SECRET
            value: "notArealSECRET_dev_only"
          - name: MONGO__CONNECTION_STRING
            value: "mongodb://mongodb:27017"
          - name: MAILER__HOSTNAME
            value: "mailer"
          - name: MAILER__PORT
            value: "80"
          - name: MAILER__DEFAULT_ORDER_TEMPLATE
            value: "receipt-full.mjml"
        volumeMounts:
          - mountPath: /workspace
            name: server
      volumes:
        - name: server
          hostPath:
            path: /workspace/server
            type: Directory
      dnsPolicy: ClusterFirst
status: {}
